### ISSUE TITLE
Increasing memory useage.

### ISSUE THREAD

**Issue by Reeniee** [ScriptLineStudios/pygame_shaders#3]
Running a simple test program with this, I've noticed it using more and more memory constantly.

In visual studio code I monitored the program performance with resource monitor.
![shader screenshot](https://user-images.githubusercontent.com/117862932/200935235-245d77c4-dd97-46ef-9b47-cdb03d1509bd.png)

Please ask if you need me to provide any more information.

**Comment by ScriptLineStudios** [comment]
Thanks for the report, this should be fixed in the latest pypi release
